import React from "react";
import {
  FileText,
  Download,
  Activity,
  ScanLine,
  ShieldCheck,
  AlertTriangle,
  Target,
  CalendarDays,
  MapPin,
  BarChart3,
} from "lucide-react";

import "./Reports.css";

const classificationData = [
  {
    name: "Marine Debris",
    count: 18,
    percentage: 45,
  },
  {
    name: "Metal Objects",
    count: 9,
    percentage: 23,
  },
  {
    name: "Unknown Anomalies",
    count: 7,
    percentage: 17,
  },
  {
    name: "Seafloor Objects",
    count: 6,
    percentage: 15,
  },
];

const recentSurveys = [
  {
    id: "SUR-2026-014",
    area: "Survey Zone Alpha",
    date: "20 Sep 2026",
    scans: 128,
    detections: 14,
    status: "Completed",
  },
  {
    id: "SUR-2026-013",
    area: "Survey Zone Beta",
    date: "18 Sep 2026",
    scans: 96,
    detections: 9,
    status: "Completed",
  },
  {
    id: "SUR-2026-012",
    area: "Survey Zone Gamma",
    date: "16 Sep 2026",
    scans: 84,
    detections: 7,
    status: "Reviewed",
  },
];

function Reports() {
  const handleExportReport = () => {
    const report = `
MARINEAI - UNDERWATER SURVEY REPORT
====================================

Survey Period:
16 – 20 Sep 2026

Survey Area:
Marine Survey Zone A

Survey Status:
Operational


------------------------------------
SURVEY SUMMARY
------------------------------------

Total Sonar Scans: 308
AI Detections: 40
Verified Detections: 27
High-Risk Findings: 6


------------------------------------
DETECTION CLASSIFICATION
------------------------------------

Marine Debris: 18 (45%)
Metal Objects: 9 (23%)
Unknown Anomalies: 7 (17%)
Seafloor Objects: 6 (15%)


------------------------------------
AI CONFIDENCE
------------------------------------

Average AI Confidence: 88.7%


------------------------------------
RECENT SURVEYS
------------------------------------

SUR-2026-014
Area: Survey Zone Alpha
Date: 20 Sep 2026
Sonar Scans: 128
Detections: 14
Status: Completed

SUR-2026-013
Area: Survey Zone Beta
Date: 18 Sep 2026
Sonar Scans: 96
Detections: 9
Status: Completed

SUR-2026-012
Area: Survey Zone Gamma
Date: 16 Sep 2026
Sonar Scans: 84
Detections: 7
Status: Reviewed


------------------------------------
REPORT STATUS
------------------------------------

Generated by MarineAI

AI-powered underwater marine debris
and anomaly detection platform.

====================================
`;

    const blob = new Blob([report], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = "MarineAI-Survey-Report.txt";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  return (
    <div className="reports-page">

      {/* ================= HEADER ================= */}

      <div className="reports-header">

        <div>
          <div className="reports-eyebrow">
            <FileText size={15} />
            SURVEY INTELLIGENCE
          </div>

          <h1>Reports & Analytics</h1>

          <p>
            Review underwater survey performance, AI detection
            statistics, anomaly classifications, and operational
            risk indicators.
          </p>
        </div>

        <button
          className="export-report-button"
          onClick={handleExportReport}
        >
          <Download size={16} />
          Export Report
        </button>

      </div>

      {/* ================= SURVEY INFO ================= */}

      <div className="survey-info-bar">

        <div className="survey-info-item">

          <CalendarDays size={16} />

          <div>
            <span>Survey Period</span>
            <strong>16 – 20 Sep 2026</strong>
          </div>

        </div>

        <div className="survey-info-item">

          <MapPin size={16} />

          <div>
            <span>Survey Area</span>
            <strong>Marine Survey Zone A</strong>
          </div>

        </div>

        <div className="survey-info-item">

          <Activity size={16} />

          <div>
            <span>Survey Status</span>

            <strong className="completed-text">
              Operational
            </strong>
          </div>

        </div>

      </div>

      {/* ================= KPI CARDS ================= */}

      <div className="reports-kpi-grid">

        {/* Total Scans */}

        <div className="report-kpi-card">

          <div className="report-kpi-icon scans">
            <ScanLine size={21} />
          </div>

          <div>
            <span>Total Sonar Scans</span>
            <strong>308</strong>
            <small>Across active surveys</small>
          </div>

        </div>

        {/* AI Detections */}

        <div className="report-kpi-card">

          <div className="report-kpi-icon detections">
            <Target size={21} />
          </div>

          <div>
            <span>AI Detections</span>
            <strong>40</strong>
            <small>Potential anomalies found</small>
          </div>

        </div>

        {/* Verified */}

        <div className="report-kpi-card">

          <div className="report-kpi-icon verified">
            <ShieldCheck size={21} />
          </div>

          <div>
            <span>Verified Detections</span>
            <strong>27</strong>
            <small>Human-reviewed records</small>
          </div>

        </div>

        {/* High Risk */}

        <div className="report-kpi-card">

          <div className="report-kpi-icon risk">
            <AlertTriangle size={21} />
          </div>

          <div>
            <span>High-Risk Findings</span>
            <strong>6</strong>
            <small>Require operational attention</small>
          </div>

        </div>

      </div>

      {/* ================= ANALYTICS ================= */}

      <div className="analytics-grid">

        {/* Classification */}

        <section className="analytics-card">

          <div className="analytics-card-header">

            <div>
              <h2>Detection Classification</h2>

              <span>
                AI-generated classification distribution
              </span>
            </div>

            <BarChart3 size={19} />

          </div>

          <div className="classification-list">

            {classificationData.map((item) => (

              <div
                className="classification-row"
                key={item.name}
              >

                <div className="classification-label">

                  <span>{item.name}</span>

                  <strong>
                    {item.count}
                  </strong>

                </div>

                <div className="classification-bar">

                  <div
                    className="classification-fill"
                    style={{
                      width: `${item.percentage}%`,
                    }}
                  ></div>

                </div>

                <span className="classification-percent">
                  {item.percentage}%
                </span>

              </div>

            ))}

          </div>

        </section>

        {/* Confidence */}

        <section className="analytics-card">

          <div className="analytics-card-header">

            <div>
              <h2>AI Confidence</h2>

              <span>
                Detection confidence overview
              </span>
            </div>

            <Target size={19} />

          </div>

          <div className="confidence-chart">

            <div className="confidence-axis">

              <span>100%</span>
              <span>75%</span>
              <span>50%</span>
              <span>25%</span>
              <span>0%</span>

            </div>

            <div className="confidence-bars">

              <div className="confidence-column">

                <div
                  className="confidence-bar high"
                  style={{ height: "88%" }}
                ></div>

                <span>High</span>

              </div>

              <div className="confidence-column">

                <div
                  className="confidence-bar medium"
                  style={{ height: "63%" }}
                ></div>

                <span>Medium</span>

              </div>

              <div className="confidence-column">

                <div
                  className="confidence-bar review"
                  style={{ height: "38%" }}
                ></div>

                <span>Review</span>

              </div>

            </div>

          </div>

          <div className="confidence-footer">

            <span>
              Average AI Confidence
            </span>

            <strong>
              88.7%
            </strong>

          </div>

        </section>

      </div>

      {/* ================= SURVEY TABLE ================= */}

      <section className="survey-table-card">

        <div className="analytics-card-header">

          <div>

            <h2>Recent Survey Reports</h2>

            <span>
              Summary of recently processed underwater surveys
            </span>

          </div>

          <FileText size={19} />

        </div>

        <div className="survey-table-wrapper">

          <table className="survey-table">

            <thead>

              <tr>

                <th>Survey ID</th>

                <th>Survey Area</th>

                <th>Date</th>

                <th>Sonar Scans</th>

                <th>Detections</th>

                <th>Status</th>

              </tr>

            </thead>

            <tbody>

              {recentSurveys.map((survey) => (

                <tr key={survey.id}>

                  <td>
                    <strong>
                      {survey.id}
                    </strong>
                  </td>

                  <td>
                    {survey.area}
                  </td>

                  <td>
                    {survey.date}
                  </td>

                  <td>
                    {survey.scans}
                  </td>

                  <td>

                    <span className="detection-count">
                      {survey.detections}
                    </span>

                  </td>

                  <td>

                    <span
                      className={`survey-status ${survey.status
                        .toLowerCase()
                        .replace(" ", "-")}`}
                    >
                      {survey.status}
                    </span>

                  </td>

                </tr>

              ))}

            </tbody>

          </table>

        </div>

      </section>

    </div>
  );
}

export default Reports;